# Generated by Django 3.2.19 on 2023-05-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_do', '0002_alter_train_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_data',
            name='user_id',
        ),
    ]
