# Generated by Django 3.2.19 on 2023-05-21 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_data_lack_health'),
        ('health_do', '0003_remove_training_data_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_data',
            name='user_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='main.user_data'),
            preserve_default=False,
        ),
    ]
